// Import NestJS dependency injection decorator
import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common'

// Import PrismaClient generated by Prisma
import { PrismaClient } from '@prisma/client'


// @Injectable allows NestJS dependency injection
// So other services can use PrismaService
@Injectable()

// PrismaService extends PrismaClient
// This means all Prisma database methods are available here
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy {


  // This lifecycle hook runs when NestJS module starts
  async onModuleInit() {

    // Connect Prisma to the database
    await this.$connect()
  }


  // This lifecycle hook runs when application shuts down
  async onModuleDestroy() {

    // Disconnect database connection
    await this.$disconnect()
  }
}